title: Karson Kalt
author:
  name: Karson Kalt
  email: kars.kalt@gmail.com
status: Currently building ts-shell, playing with WebGL, working on my site
status_updated: 2024-08-01

collections:
  notes:
    output: true

include:
  - _data

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - assets/ts
