title: Karson Kalt
author:
  name: Karson Kalt
  email: kars.kalt@gmail.com
status: Currently learning AWS/IaC
status_updated: 2024-07-06

collections:
  notes:
    output: true

include:
  - _data

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - assets/ts
