title: Karson Kalt
author:
  name: Karson Kalt
  email: kars.kalt@gmail.com
status: Learning AWS/IaC, listening to a lot of Jamiroquai

collections:
  notes:
    output: true

include:
  - _data

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - assets/ts
