title: Karson Kalt
author:
  name: Karson Kalt
  email: kars.kalt@gmail.com
status:
  Currently working on upgrading observability dashboards, filtering, query
  variables, and data visualization at JupiterOne.
status_updated: 2024-09-26

collections:
  notes:
    output: true

include:
  - _data

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - node_modules
  - assets/ts
